
name: Deploy to Now
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 # Equivalent to `git checkout master`

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: now install
        run : yarn global add now

      - name: Deploy
        run: now --prod -t ${{ secrets.ZEIT_TOKEN }}

        # The `_build/` argument is optional. In my case it's the directory where `yarn build` puts the final code to
        # deploy. If you want to deploy the current directory instead, just remove this argument.